- item_type: PORTS
  ports_list:
    - port: '80'
- item_type: SERVICES
  service_list:
    - name: TCP
- item_type: NODE
  node_id: '1'
  name: PC1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.2
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '2'
  name: SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.3
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '3'
  name: PC2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.4
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '4'
  name: SWITCH1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.5
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '5'
  name: SWITCH2
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.6
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '6'
  name: SWITCH3
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.7
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '7'
  name: SWITCH4
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.8
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '8'
  name: SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.9
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '9'
  name: SWITCH5
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.10
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '10'
  name: SWITCH6
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.11
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '11'
  name: PC3
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '12'
  name: PC4
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.13
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '13'
  name: PC5
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.14
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '14'
  name: PC6
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.15
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '15'
  name: PC7
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.16
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '16'
  name: PC8
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.17
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: LINK
  id: '17'
  name: link16
  bandwidth: 1000000000
  source: '14'
  destination: '10'
- item_type: LINK
  id: '18'
  name: link17
  bandwidth: 1000000000
  source: '15'
  destination: '10'
- item_type: LINK
  id: '19'
  name: link18
  bandwidth: 1000000000
  source: '16'
  destination: '10'
- item_type: LINK
  id: '20'
  name: link15
  bandwidth: 1000000000
  source: '12'
  destination: '4'
- item_type: LINK
  id: '21'
  name: link14
  bandwidth: 1000000000
  source: '13'
  destination: '4'
- item_type: LINK
  id: '22'
  name: link13
  bandwidth: 1000000000
  source: '11'
  destination: '4'
- item_type: LINK
  id: '23'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '4'
- item_type: LINK
  id: '24'
  name: link2
  bandwidth: 1000000000
  source: '4'
  destination: '2'
- item_type: LINK
  id: '25'
  name: link3
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- item_type: LINK
  id: '26'
  name: link4
  bandwidth: 1000000000
  source: '2'
  destination: '6'
- item_type: LINK
  id: '27'
  name: link5
  bandwidth: 1000000000
  source: '5'
  destination: '3'
- item_type: LINK
  id: '28'
  name: link6
  bandwidth: 1000000000
  source: '6'
  destination: '3'
- item_type: LINK
  id: '29'
  name: link7
  bandwidth: 1000000000
  source: '1'
  destination: '7'
- item_type: LINK
  id: '30'
  name: link8
  bandwidth: 1000000000
  source: '8'
  destination: '9'
- item_type: LINK
  id: '31'
  name: link9
  bandwidth: 1000000000
  source: '8'
  destination: '10'
- item_type: LINK
  id: '32'
  name: link10
  bandwidth: 1000000000
  source: '7'
  destination: '8'
- item_type: LINK
  id: '33'
  name: link11
  bandwidth: 1000000000
  source: '1'
  destination: '9'
- item_type: LINK
  id: '34'
  name: link12
  bandwidth: 1000000000
  source: '3'
  destination: '10'
- item_type: GREEN_IER
  id: '13'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  mission_criticality: 5
- item_type: RED_POL
  id: '14'
  start_step: 50
  end_step: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '15'
  start_step: 60
  end_step: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  mission_criticality: 0
- item_type: RED_POL
  id: '16'
  start_step: 70
  end_step: 70
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '14'
  start_step: 50
  end_step: 50
  targetNodeId: '3'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '15'
  start_step: 60
  end_step: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '2'
  mission_criticality: 0
- item_type: RED_POL
  id: '16'
  start_step: 80
  end_step: 80
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: ACL_RULE
  id: '17'
  permission: ALLOW
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
  position: 0
