- item_type: PORTS
  ports_list:
    - port: '80'
- item_type: SERVICES
  service_list:
    - name: TCP
- item_type: NODE
  node_id: '1'
  name: PC1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.2
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '2'
  name: SERVER1
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.3
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '3'
  name: PC2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.4
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '4'
  name: SWITCH1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.5
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '5'
  name: SWITCH2
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.6
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '6'
  name: SWITCH3
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.7
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '7'
  name: SWITCH4
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.8
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '8'
  name: SERVER2
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.9
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '9'
  name: SWITCH5
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.10
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '10'
  name: SWITCH6
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.11
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '11'
  name: PC3
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '12'
  name: PC4
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.13
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '13'
  name: PC5
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.14
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '14'
  name: PC6
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.15
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '15'
  name: PC7
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.16
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '16'
  name: PC8
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.17
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '17'
  name: SERVER3
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.18
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '18'
  name: SERVER4
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.19
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '19'
  name: SERVER5
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.20
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '20'
  name: SERVER6
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.21
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '21'
  name: PC9
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.22
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '22'
  name: PC10
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.23
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '23'
  name: SWITCH7
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.24
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '24'
  name: SWITCH8
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.25
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '25'
  name: SERVER7
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.26
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '26'
  name: SWITCH9
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.27
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '27'
  name: SWITCH10
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.28
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '28'
  name: SERVER8
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.29
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '29'
  name: SWITCH11
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.30
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '30'
  name: SERVER9
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.31
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: LINK
  id: '31'
  name: link1
  bandwidth: 1000000000
  source: '14'
  destination: '10'
- item_type: LINK
  id: '32'
  name: link2
  bandwidth: 1000000000
  source: '15'
  destination: '10'
- item_type: LINK
  id: '33'
  name: link3
  bandwidth: 1000000000
  source: '16'
  destination: '10'
- item_type: LINK
  id: '34'
  name: link4
  bandwidth: 1000000000
  source: '12'
  destination: '4'
- item_type: LINK
  id: '35'
  name: link5
  bandwidth: 1000000000
  source: '13'
  destination: '4'
- item_type: LINK
  id: '36'
  name: link6
  bandwidth: 1000000000
  source: '11'
  destination: '4'
- item_type: LINK
  id: '37'
  name: link7
  bandwidth: 1000000000
  source: '1'
  destination: '4'
- item_type: LINK
  id: '38'
  name: link8
  bandwidth: 1000000000
  source: '4'
  destination: '2'
- item_type: LINK
  id: '39'
  name: link9
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- item_type: LINK
  id: '40'
  name: link10
  bandwidth: 1000000000
  source: '2'
  destination: '6'
- item_type: LINK
  id: '41'
  name: link11
  bandwidth: 1000000000
  source: '5'
  destination: '3'
- item_type: LINK
  id: '42'
  name: link12
  bandwidth: 1000000000
  source: '6'
  destination: '3'
- item_type: LINK
  id: '43'
  name: link13
  bandwidth: 1000000000
  source: '1'
  destination: '7'
- item_type: LINK
  id: '44'
  name: link14
  bandwidth: 1000000000
  source: '8'
  destination: '9'
- item_type: LINK
  id: '45'
  name: link15
  bandwidth: 1000000000
  source: '8'
  destination: '10'
- item_type: LINK
  id: '46'
  name: link16
  bandwidth: 1000000000
  source: '7'
  destination: '8'
- item_type: LINK
  id: '47'
  name: link17
  bandwidth: 1000000000
  source: '1'
  destination: '9'
- item_type: LINK
  id: '48'
  name: link18
  bandwidth: 1000000000
  source: '3'
  destination: '10'
- item_type: LINK
  id: '49'
  name: link19
  bandwidth: 1000000000
  source: '6'
  destination: '17'
- item_type: LINK
  id: '50'
  name: link20
  bandwidth: 1000000000
  source: '6'
  destination: '18'
- item_type: LINK
  id: '51'
  name: link21
  bandwidth: 1000000000
  source: '7'
  destination: '19'
- item_type: LINK
  id: '52'
  name: link22
  bandwidth: 1000000000
  source: '7'
  destination: '20'
- item_type: LINK
  id: '53'
  name: link23
  bandwidth: 1000000000
  source: '21'
  destination: '4'
- item_type: LINK
  id: '54'
  name: link24
  bandwidth: 1000000000
  source: '22'
  destination: '10'
- item_type: LINK
  id: '55'
  name: link25
  bandwidth: 1000000000
  source: '17'
  destination: '23'
- item_type: LINK
  id: '56'
  name: link26
  bandwidth: 1000000000
  source: '17'
  destination: '24'
- item_type: LINK
  id: '57'
  name: link27
  bandwidth: 1000000000
  source: '23'
  destination: '25'
- item_type: LINK
  id: '58'
  name: link28
  bandwidth: 1000000000
  source: '24'
  destination: '25'
- item_type: LINK
  id: '59'
  name: link29
  bandwidth: 1000000000
  source: '18'
  destination: '26'
- item_type: LINK
  id: '60'
  name: link30
  bandwidth: 1000000000
  source: '18'
  destination: '27'
- item_type: LINK
  id: '61'
  name: link31
  bandwidth: 1000000000
  source: '26'
  destination: '28'
- item_type: LINK
  id: '62'
  name: link32
  bandwidth: 1000000000
  source: '27'
  destination: '28'
- item_type: LINK
  id: '63'
  name: link33
  bandwidth: 1000000000
  source: '19'
  destination: '29'
- item_type: LINK
  id: '64'
  name: link34
  bandwidth: 1000000000
  source: '20'
  destination: '29'
- item_type: LINK
  id: '65'
  name: link35
  bandwidth: 1000000000
  source: '29'
  destination: '30'
- item_type: GREEN_IER
  id: '66'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '67'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '11'
  destination: '8'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '68'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '21'
  destination: '30'
  mission_criticality: 5
- item_type: RED_POL
  id: '69'
  start_step: 50
  end_step: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '70'
  start_step: 60
  end_step: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  mission_criticality: 0
- item_type: RED_POL
  id: '71'
  start_step: 70
  end_step: 70
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '72'
  start_step: 50
  end_step: 50
  targetNodeId: '3'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '73'
  start_step: 60
  end_step: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '2'
  mission_criticality: 0
- item_type: RED_POL
  id: '74'
  start_step: 80
  end_step: 80
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '75'
  start_step: 30
  end_step: 30
  targetNodeId: '11'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '76'
  start_step: 32
  end_step: 72
  load: 1000000
  protocol: TCP
  port: '80'
  source: '11'
  destination: '19'
  mission_criticality: 0
- item_type: RED_POL
  id: '77'
  start_step: 40
  end_step: 40
  targetNodeId: '19'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '78'
  start_step: 40
  end_step: 40
  targetNodeId: '14'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '79'
  start_step: 50
  end_step: 90
  load: 1000000
  protocol: TCP
  port: '80'
  source: '14'
  destination: '30'
  mission_criticality: 0
- item_type: RED_POL
  id: '80'
  start_step: 70
  end_step: 70
  targetNodeId: '30'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: ACL_RULE
  id: '59'
  permission: ALLOW
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
  position: 0
