- item_type: PORTS
  ports_list:
    - port: '80'
- item_type: SERVICES
  service_list:
    - name: TCP
- item_type: NODE
  node_id: '1'
  name: PC1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.30.11
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '2'
  name: PC2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.30.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '3'
  name: PC3
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.30.13
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '4'
  name: PC4
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.40.14
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '5'
  name: SWITCH1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.3.2
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '6'
  name: IDS
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.4
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '7'
  name: SWITCH2
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.3
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '8'
  name: LOP1
  node_class: SERVICE
  node_type: LOP
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '9'
  name: SERVER1
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.10.14
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '10'
  name: SERVER2
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.20.15
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '11'
  name: PC5
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.10.11
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '12'
  name: PC6
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.10.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '13'
  name: PC7
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.10.13
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '14'
  name: PC8
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.20.14
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '15'
  name: SWITCH3
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.2
  software_state: GOOD
  file_system_state: GOOD
- item_type: LINK
  id: '16'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '5'
- item_type: LINK
  id: '17'
  name: link2
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- item_type: LINK
  id: '18'
  name: link3
  bandwidth: 1000000000
  source: '3'
  destination: '5'
- item_type: LINK
  id: '19'
  name: link4
  bandwidth: 1000000000
  source: '4'
  destination: '5'
- item_type: LINK
  id: '20'
  name: link5
  bandwidth: 1000000000
  source: '5'
  destination: '6'
- item_type: LINK
  id: '21'
  name: link6
  bandwidth: 1000000000
  source: '5'
  destination: '8'
- item_type: LINK
  id: '22'
  name: link7
  bandwidth: 1000000000
  source: '6'
  destination: '7'
- item_type: LINK
  id: '23'
  name: link8
  bandwidth: 1000000000
  source: '8'
  destination: '7'
- item_type: LINK
  id: '24'
  name: link9
  bandwidth: 1000000000
  source: '7'
  destination: '9'
- item_type: LINK
  id: '25'
  name: link10
  bandwidth: 1000000000
  source: '7'
  destination: '10'
- item_type: LINK
  id: '26'
  name: link11
  bandwidth: 1000000000
  source: '11'
  destination: '15'
- item_type: LINK
  id: '27'
  name: link12
  bandwidth: 1000000000
  source: '12'
  destination: '15'
- item_type: LINK
  id: '28'
  name: link12
  bandwidth: 1000000000
  source: '13'
  destination: '15'
- item_type: LINK
  id: '29'
  name: link13
  bandwidth: 1000000000
  source: '14'
  destination: '15'
- item_type: LINK
  id: '30'
  name: link14
  bandwidth: 1000000000
  source: '15'
  destination: '8'
- item_type: LINK
  id: '31'
  name: link15
  bandwidth: 1000000000
  source: '15'
  destination: '6'
- item_type: GREEN_IER
  id: '32'
  start_step: 21
  end_step: 148
  load: 100000
  protocol: TCP
  port: '80'
  source: '11'
  destination: '9'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '33'
  start_step: 21
  end_step: 148
  load: 100000
  protocol: TCP
  port: '80'
  source: '12'
  destination: '9'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '34'
  start_step: 21
  end_step: 148
  load: 100000
  protocol: TCP
  port: '80'
  source: '9'
  destination: '13'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '35'
  start_step: 21
  end_step: 148
  load: 100000
  protocol: TCP
  port: '80'
  source: '14'
  destination: '10'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '36'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '9'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '37'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '9'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '38'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '9'
  destination: '3'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '39'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '4'
  destination: '10'
  mission_criticality: 2
- item_type: RED_POL
  id: '40'
  start_step: 20
  end_step: 20
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '41'
  start_step: 20
  end_step: 20
  targetNodeId: '2'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '42'
  start_step: 30
  end_step: 128
  load: 440000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '9'
  mission_criticality: 0
- item_type: RED_IER
  id: '43'
  start_step: 30
  end_step: 128
  load: 440000000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '9'
  mission_criticality: 0
- item_type: RED_POL
  id: '44'
  start_step: 30
  end_step: 30
  targetNodeId: '9'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: OVERWHELMED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '45'
  start_step: 40
  end_step: 40
  targetNodeId: '11'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '46'
  start_step: 130
  end_step: 130
  targetNodeId: '12'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '47'
  start_step: 140
  end_step: 200
  load: 440000000
  protocol: TCP
  port: '80'
  source: '11'
  destination: '10'
  mission_criticality: 0
- item_type: RED_IER
  id: '48'
  start_step: 140
  end_step: 200
  load: 440000000
  protocol: TCP
  port: '80'
  source: '12'
  destination: '10'
  mission_criticality: 0
- item_type: RED_POL
  id: '49'
  start_step: 140
  end_step: 140
  targetNodeId: '10'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: OVERWHELMED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
